### PR TITLE
Implementation of React Router v4

### PR DESCRIPTION
**Pull request by kirill-konshin**

### CODE REVIEW

**Comment by diligiant** [comment]
@kirill-konshin thank you. I am trying to dig into your work; in a client env, I use (like recommended)
```
<Provider store=…>
  <ConnectedRouter history=…>
```
(all this being wrapped for dev purposes by react-hot-loader AppContainer ;)

In your example, you seem to reshuffle the order to
```
<BrowserRouter>
  <Provider store=…>
    <WrapperProvider …>
```
Which would, in the client environment, disconnect the Router from the provider. Are you taking care of the wiring in WrapperProvider (in effect, replacing ConnectedRouter), allowing me to just remove ConnectedRouter in the server env ?

**Comment by kirill-konshin** [comment]
`Provider` and `Router` don't know about each other at all, so order should not be important, but both must be before `WrapperProvider` in order to provide context to it. Did you have any issues with that? If yes, please create a separate issue, this is a pull request for next version of RR.

**Comment by diligiant** [comment]
Yes and no ;) [ConnectedRouter](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux) knows about Provider (the only reason it exists really ;)

In server-side mode, ConnectedRouter is gone (I assume it's done by your Wrapper) so, in a redux context, I was wondering if you have any issue with a « swap » between WrapperPrivider and ConnectedRouter?

**Comment by kirill-konshin** [comment]
Oh, you were talking about `react-router-redux`. `WrapperProvider` must have both `Provider` and `ConnectedRouter` in context.

> ConnectedRouter is gone (I assume it's done by your Wrapper)

`WrapperProvider` does not do anything with Router except it takes things from its' context.

**Comment by diligiant** [comment]
But in your [example](https://github.com/kirill-konshin/create-react-server/pull/2/commits/e7de3dde26c43b047b3e675dbe1853de01a93a2b#diff-554b9ce8d206a95abc33ae93c569a599R9), `<BrowserRouter>` is out of the picture as `create-react-server` is provided with `app.js` which only has `Provider` & `WrapperProvider` in its "hierarchy" ??

You lost me here 🤗

**Comment by kirill-konshin** [comment]
You are looking at routes config, router itself is defined in different file: https://github.com/kirill-konshin/create-react-server/blob/master/examples/create-react-app/src/index.js.

**Comment by diligiant** [comment]
that's 0.2, I'm on your 0.3 branch for React Router 4.

**Comment by kirill-konshin** [comment]
The reason for this was some weird behavior of HMR in React Router... Technically `WrapperProvider` does not care about the order.

**Comment by diligiant** [comment]
Thank you. You mean I can have the same combo in CS & SS ?
```
<Provider…
  <ConnectedRouter…
    <WrapperProvider
```
that would be awesome!

**Comment by kirill-konshin** [comment]
There should be no problem.

Keep in mind that CRS does not support async routes yet, at least w/o static route configuration... that's the only reason why it's not released yet :(

Please keep me posted about your experience with 0.3.0 branch!

**Comment by diligiant** [comment]
of course. So cool ;)

**Comment by diligiant** [comment]
@kirill-konshin I wonder if you might have an idea: node is choking at `var creator = require(pathAbs);` in my project with either
`SyntaxError: Unexpected token export`
or
`SyntaxError: Unexpected token import`

And when I say my project, what matters is not my source file (and empty src with your app.js fails too) but my node_modules (a standard ejected 1.0.7 create-react-app). If I put your example node_modules in my project, it doesn't choke.

I wonder if you had ANY idea as it sounds laborious to find blinded ;)

**Comment by diligiant** [comment]
@kirill-konshin I'm facing an issue you might have already encountered. babel-preset-react-app is now 3.x. When up to date in the react-app, `var creator = require(pathAbs);` fails with either a `SyntaxError: Unexpected token export` or `SyntaxError: Unexpected token import`.

All you need is a minimal app.js (empty function) and
```
 "devDependencies": {
    "babel-core": "6.25.0",
    "babel-preset-react-app": "^3.0.0"
```

**Comment by kirill-konshin** [comment]
How is this related to this package? Maybe you should talk to authors of preset.

**Comment by diligiant** [comment]
Because as soon as babel-preset-react-app is updated to the latest version (and that's mandatory for recent create-react-app packages), even your create-react-app example suffers the same problem ;)

**Comment by kirill-konshin** [comment]
Have you reported that to authors?

**Comment by diligiant** [comment]
I would if the bug was theirs but the exception is raised only by server.js `require(pathAbs)`. Somehow it's incompatible with latest create-react-app. I wish I knew why and how to fix it. node/babel message is cryptic and NODE_DEBUG dumps too much info for me.

I'll keep looking but I was wondering if you encountered the problem which would explain why you stick to old create-react-app versions.

**Comment by diligiant** [comment]
Yes, I am reporting to you that you cra example doesn't work with latest cra ;)
If the preset was bad, we would know as it builds a fairly large project.

I spent a lot of time with node --inspect and NODE_DEBUG to no success. The reason why I asked you as that might have been the reason why cra versions are a bit behind.

**Comment by kirill-konshin** [comment]
I will look into it

**Comment by kirill-konshin** [comment]
I reproduced the error, will fix it as soon as I can. Looks like Babel no longer compiles files in certain paths, so I either have to reconfigure it or do something else.

**Comment by diligiant** [comment]
thank you!

**Comment by kirill-konshin** [comment]
Closing this PR because discussion has diverted far away from original purpose of this PR. Next time pls create separate issues for each question :)

Please see issue #3, I have a fix now, but I need to test it more and I will push it today/tomorrow.

**Pull request closed without merging**
